### ISSUE TITLE
Bug when calling write_uvfits

### ISSUE THREAD

**Issue by wenyang-li** [HERA-Team/pyuvdata#20]
When I read in a uvfits file from FHD_prep.py, make some changes to the data_array only, and then write out a new uvfits file using write_uvfits, some problem comes out when writing history, the error message is like this: 

Traceback (most recent call last):
  File "/Users/wenyangli/eoranalysis/db/capo/omni/omni_apply_ucla.py", line 97, in <module>
    uvi.write_uvfits(newfile)
  File "/Users/wenyangli/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/uvdata/uv.py", line 759, in write_uvfits
    hdu.header['HISTORY '] = self.history.value
  File "/Users/wenyangli/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/astropy/io/fits/header.py", line 195, in __setitem__
    self._update((key, value, comment))
  File "/Users/wenyangli/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/astropy/io/fits/header.py", line 1678, in _update
    self.append(card)
  File "/Users/wenyangli/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/astropy/io/fits/header.py", line 1226, in append
    card = Card(*card)
  File "/Users/wenyangli/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/astropy/io/fits/card.py", line 448, in __init__
    self.value = value
  File "/Users/wenyangli/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/astropy/io/fits/card.py", line 603, in value
    'represent printable characters in ASCII.' % value)
ValueError: FITS header values must contain standard printable ASCII characters; 'MDLVIS: created file.\nMDLVIS: /Users/wenyangli/eoranalysis/db/aipy/scripts/mdlvis.py -s for,pi\nsdf=.0005 --inttime=10.0 --startjd=2455930.24787 --endjd=2455930.24926 -\nFHD_prep:/Users/wenyangli/eoranalysis/db/brownscripts/jcp/FHD_prep.py -C\nFITS: Miriad fits: fits: CVS Revision (not recorded)\nFITS: Executed on: 16MAY11:16:21:22.0\nFITS: Command line inputs follow:\nFITS:    in=zen.2455930.24787.xx.uvM\nFITS:    op=uvout\nFITS:    out=zen.2455930.24787.xx.uvM.uvfits\nFITS: NOTE: Use options=varwt if loading into Miriad\nAIPS WTSCAL =  1.00000000000E+00' contains characters/bytes that do not represent printable characters in ASCII.

**Comment by jpober** [comment]
Will come up with test for producing this error.

**Comment by jpober** [comment]
Fixed.
