### ISSUE TITLE
UVCal reader gives "IOError: Header missing END card" when number of antennas in calfits files changes

### ISSUE THREAD

**Issue by AaronParsons** [HERA-Team/pyuvdata#253]
I'm not sure whether the solution is to make UVCal able to deal with the number of antennas in a calfits file changing, or to give a clearer error message that indicates that this error is a result of the number of antennas in the file changing.

Here's the error that is raised:
```Traceback (most recent call last):
  File "/Users/aparsons/pkgs/hera/hera_sandbox/arp/scripts/plot_calfits.py", line 11, in <module>
    oc.read_calfits(omni_files)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyuvdata-1.1-py2.7.egg/pyuvdata/uvcal.py", line 589, in read_calfits
    strict_fits=strict_fits)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyuvdata-1.1-py2.7.egg/pyuvdata/uvcal.py", line 597, in read_calfits
    strict_fits=strict_fits)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyuvdata-1.1-py2.7.egg/pyuvdata/calfits.py", line 328, in read_calfits
    F = fits.open(filename)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 158, in fitsopen
    lazy_load_hdus, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 411, in fromfile
    lazy_load_hdus=lazy_load_hdus, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 1021, in _readfrom
    read_one = hdulist._read_next_hdu()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 1096, in _read_next_hdu
    hdu = _BaseHDU.readfrom(fileobj, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/io/fits/hdu/base.py", line 332, in readfrom
    **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/io/fits/hdu/base.py", line 397, in _readfrom_internal
    header = Header.fromfile(data, endcard=not ignore_missing_end)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/io/fits/header.py", line 449, in fromfile
    padding)[1]
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/io/fits/header.py", line 518, in _from_blocks
    raise IOError('Header missing END card.')
IOError: Header missing END card.'''

**Comment by plaplant** [comment]
I am not able to reproduce this just by reading in calfits files with different numbers of antennas into the same object. @AaronParsons can you upload the script you're using that causes this error?

**Comment by bhazelton** [comment]
@AaronParsons we haven't been able to reproduce this error. Is it still a problem?

**Comment by bhazelton** [comment]
We can't reproduce this error and haven't heard anything for a month, so I'm going to close this issue. Feel free to reopen it if it's still a problem, but please provide details to reproduce it.
