### ISSUE TITLE
Multi-pol miriad files can't be read

### ISSUE THREAD

**Issue by jpober** [HERA-Team/pyuvdata#48]
read_miriad fails on certain files; the cause seems to be multiple polarizations, although the error message isn't too clear:

Traceback (most recent call last):
  File "./test.py", line 10, in <module>
    uvd.read_miriad('zen.2455819.53765.uvcRRE')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/uvdata/uv.py", line 776, in read_miriad
    run_check=True, run_sanity_check=True)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/uvdata/miriad.py", line 123, in read_miriad
    np.ravel([[k[1] for k in d] for d in data_accumulator.values()])))

It looks like when there are multiple polarizations, the list comprehension returns a data_accumulator.values[0] as a list, but it's a float (which is needed to work) when there is only one polarization.  The actual error occurs when we try to take a 'set' of the 'np.ravel'-ed array.

**Comment by jpober** [comment]
The error has been fixed.  ravel needed to be replaced with concatenate.
